--CREATE TYPE
CREATE TYPE status_employee AS ENUM ('active', 'on leave', 'on vacation', 'dismissed');
CREATE TYPE status_inventory AS ENUM ('pending', 'in review', 'approved');
-------------
--REF
CREATE TABLE address (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  street VARCHAR(255),
  number VARCHAR(20),
  complement VARCHAR(100),
  city VARCHAR(100),
  state VARCHAR(100),
  country VARCHAR(100)
);

CREATE TABLE unit (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  id_company INT,
  id_address INT,
  cnpj VARCHAR(50),
  cnae VARCHAR(50),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE company (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_address INT,
  name VARCHAR(255),
  size INT CHECK (size>0),
  registration_date DATE,
  tax_id VARCHAR(50),
  email VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_address) REFERENCES address (id)
);

CREATE TABLE telephone (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telephone VARCHAR(20),
  id_company INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_company) REFERENCES company(id)
);

CREATE TABLE sector (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(255),
  id_unit INT,
  id_company INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_company) REFERENCES company (id),
  FOREIGN KEY(id_unit) REFERENCES unit (id)
);

CREATE TABLE permission_group (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100)
);

CREATE TABLE administrator (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255),
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-------------
-- EMPLOYEE 
CREATE TABLE employee (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_company INT,
  id_permission_group INT,
  name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255),
  status status_employee NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_company) REFERENCES company (id),
  FOREIGN KEY(id_permission_group) REFERENCES permission_group (id)
);

CREATE TABLE employee_telephone (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telephone VARCHAR(20),
  id_employee INT,
  FOREIGN KEY (id_employee) REFERENCES employee(id)
);

CREATE TABLE contract (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_employee INT,
  id_company INT,
  FOREIGN KEY (id_employee) REFERENCES employee(id),
  FOREIGN KEY (id_company) REFERENCES company(id)
);
----------------
--INVENTORY
CREATE TABLE inventory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_company INT,
  id_employee INT,
  id_sector INT,
  file_size FLOAT CHECK (file_size>0),
  status status_inventory DEFAULT 'pending',
  file_path VARCHAR(255),
  start_period DATE NOT NULL,
  end_period DATE NOT NULL CHECK (end_period>start_period),
  submission_date DATE,
  type VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_company) REFERENCES company(id),
  FOREIGN KEY(id_employee) REFERENCES employee (id),
  FOREIGN KEY(id_sector) REFERENCES sector (id)
);
----------------------------
--SUBSCRIPTION / PAYMENT
CREATE TABLE plan (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  description VARCHAR(255),
  price FLOAT CHECK (price>0),
  currency VARCHAR(10)
);

CREATE TABLE subscription (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_company INT,
  id_plan INT, 
  is_active BOOLEAN DEFAULT false,
  installments BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_company) REFERENCES company (id),
  FOREIGN KEY(id_plan) REFERENCES plan (id)
);

CREATE TABLE payment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency VARCHAR(10),
  id_subscription INT,
  additional_use_value FLOAT, 
  due_date DATE,
  payment_type VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_subscription) REFERENCES subscription (id)
);
---------------
-- ROI
CREATE TABLE roi_analysis (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inventory INT,
  calculation_date DATE,
  years_along INT,
  annual_operating_savings FLOAT,
  estimated_payback_month FLOAT,
  carbon_credit_revenue FLOAT,
  annual_rate_technology_degradation FLOAT,
  wacc FLOAT,
  FOREIGN KEY (id_inventory) REFERENCES inventory(id)
);

CREATE TABLE roi_projection_year (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_roi_analysis INT,
  year INT,
  value FLOAT,
  FOREIGN KEY (id_roi_analysis) REFERENCES roi_analysis(id)
);
---------------
-- GAS 

CREATE TABLE gas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  type VARCHAR(100),
  measurement VARCHAR(50),
  gwp FLOAT
);


CREATE TABLE sector_gas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sector INT,
  id_gas INT,
  FOREIGN KEY (id_sector) REFERENCES sector(id),
  FOREIGN KEY (id_gas) REFERENCES gas(id)
);

CREATE TABLE gas_reduction 
( 
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
  id_gas INT,  
  unit VARCHAR(50),  
  current_emission FLOAT,  
  estimated_days INT,  
  estimated_reduction FLOAT,  
  estimated_roi FLOAT,  
  init_emission FLOAT,  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(id_gas) REFERENCES gas (id),
);

CREATE TABLE reduction_gas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_gas_reduction INT,
  id_gas INT,
  FOREIGN KEY (id_gas_reduction) REFERENCES gas_reduction(id),
  FOREIGN KEY (id_gas) REFERENCES gas(id)
);

CREATE TABLE gas_reduction_inventory
( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_gas_reduction INT,  
  id_inventory INT,   
  FOREIGN KEY(id_gasReduction) REFERENCES gas_reduction (id),
  FOREIGN KEY(id_inventory) REFERENCES inventory (id)
); 

CREATE TABLE gas_reduction_sector 
( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  id_gas_reduction INT,  
  id_sector INT,  
  FOREIGN KEY(id_gasReduction) REFERENCES gas_reduction (id),
  FOREIGN KEY(id_sector) REFERENCES sector (id)
  
);

CREATE TABLE parana_climate_seal (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_achievement DATE,
  current_score FLOAT 
);

CREATE TABLE contains 
( id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
  id_parana_climate_seal INT,  
  id_company INT,   
  FOREIGN KEY(id_parana_climate_seal) REFERENCES parana_climate_seal (id),
  FOREIGN KEY(id_company) REFERENCES company (id)
);
---------------------
-- UNITS / ADDRESS

CREATE TABLE company_address (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_company INT,
  id_address INT,
  FOREIGN KEY (id_company) REFERENCES company(id),
  FOREIGN KEY (id_address) REFERENCES address(id)
);

CREATE TABLE unit_address (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_unit INT,
  id_address INT,
  FOREIGN KEY (id_unit) REFERENCES unit(id),
  FOREIGN KEY (id_address) REFERENCES address(id)
);
------------------------
-- PERMISSIONS
CREATE TABLE permission (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  description VARCHAR(255)
);

CREATE TABLE permission_group_permission (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_permission_group INT,  
  id_permission INT,  , 
  FOREIGN KEY(id_permission) REFERENCES permission (id),
  FOREIGN KEY(id_permission_group) REFERENCES permission_group (id)
);
